[build]
  command = waitress-serve --listen=0.0.0.0:8080 app:application"
  publish = "app/static"
  environment = { PYTHON_VERSION = "3.12" }

[dev]
  framework = "#custom"

[functions]
  included_files = ["app/*"]