[build]
  command = "pip install -r requirements.txt && gunicorn --bind 0.0.0.0:8080 app:app"  
  publish = "app/static"
  environment = { PYTHON_VERSION = "3.12" }

[dev]
  framework = "#custom"

[functions]
  included_files = ["app/*"]